package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.BgPicture;
import com.mida.chromeext.pojo.BgPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BgPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int countByExample(BgPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int deleteByExample(BgPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int insert(BgPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int insertSelective(BgPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    List<BgPicture> selectByExample(BgPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    BgPicture selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") BgPicture record, @Param("example") BgPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByExample(@Param("record") BgPicture record, @Param("example") BgPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByPrimaryKeySelective(BgPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByPrimaryKey(BgPicture record);
}