package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.ContriesSites;
import java.util.List;

public interface ContriesSitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contries_sites
     *
     * @mbggenerated
     */
    int insert(ContriesSites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contries_sites
     *
     * @mbggenerated
     */
    List<ContriesSites> selectAll();
}