package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.CountriesSite;
import com.mida.chromeext.pojo.CountriesSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountriesSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int countByExample(CountriesSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int deleteByExample(CountriesSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int insert(CountriesSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int insertSelective(CountriesSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    List<CountriesSite> selectByExample(CountriesSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") CountriesSite record, @Param("example") CountriesSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByExample(@Param("record") CountriesSite record, @Param("example") CountriesSiteExample example);
}