package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.Countries;
import java.util.List;

public interface CountriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Byte cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbggenerated
     */
    int insert(Countries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbggenerated
     */
    Countries selectByPrimaryKey(Byte cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbggenerated
     */
    List<Countries> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Countries record);
}