package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.CountriesSites;
import java.util.List;

public interface CountriesSitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated
     */
    int insert(CountriesSites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries_sites
     *
     * @mbggenerated
     */
    List<CountriesSites> selectAll();
}