package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.Sites;
import java.util.List;

public interface SitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int insert(Sites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    Sites selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    List<Sites> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sites record);
}