package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.SiteCategory;
import com.mida.chromeext.pojo.SiteCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int countByExample(SiteCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int deleteByExample(SiteCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int insert(SiteCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int insertSelective(SiteCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    List<SiteCategory> selectByExample(SiteCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    SiteCategory selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SiteCategory record, @Param("example") SiteCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int updateByExample(@Param("record") SiteCategory record, @Param("example") SiteCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int updateByPrimaryKeySelective(SiteCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    int updateByPrimaryKey(SiteCategory record);
}