package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.SiteViewHistories;
import java.util.List;

public interface SiteViewHistoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_view_histories
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_view_histories
     *
     * @mbggenerated
     */
    int insert(SiteViewHistories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_view_histories
     *
     * @mbggenerated
     */
    SiteViewHistories selectByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_view_histories
     *
     * @mbggenerated
     */
    List<SiteViewHistories> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_view_histories
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SiteViewHistories record);
}