package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.UserSite;
import com.mida.chromeext.pojo.UserSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sites
     *
     * @mbggenerated
     */
    int countByExample(UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sites
     *
     * @mbggenerated
     */
    int deleteByExample(UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sites
     *
     * @mbggenerated
     */
    int insert(UserSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sites
     *
     * @mbggenerated
     */
    int insertSelective(UserSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sites
     *
     * @mbggenerated
     */
    List<UserSite> selectByExample(UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sites
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserSite record, @Param("example") UserSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_sites
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserSite record, @Param("example") UserSiteExample example);
}