package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.UserSetting;
import com.mida.chromeext.pojo.UserSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int countByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int deleteByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int insert(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int insertSelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    List<UserSetting> selectByExampleWithBLOBs(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    List<UserSetting> selectByExample(UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    UserSetting selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserSetting record, @Param("example") UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") UserSetting record, @Param("example") UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByExample(@Param("record") UserSetting record, @Param("example") UserSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByPrimaryKeySelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated Tue Sep 17 16:08:46 CST 2019
     */
    int updateByPrimaryKey(UserSetting record);
}