package com.mida.chromeext.mapper;

import com.mida.chromeext.pojo.UserSettings;
import java.util.List;

public interface UserSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated
     */
    int insert(UserSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated
     */
    UserSettings selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated
     */
    List<UserSettings> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserSettings record);
}