package com.mida.chromeext.pojo;

import java.io.Serializable;
import java.util.Date;

public class BgPicture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_pictures.pid
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_pictures.src
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_pictures.title
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_pictures.created_by
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_pictures.created_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bg_pictures
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_pictures.pid
     *
     * @return the value of bg_pictures.pid
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_pictures.pid
     *
     * @param pid the value for bg_pictures.pid
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_pictures.src
     *
     * @return the value of bg_pictures.src
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_pictures.src
     *
     * @param src the value for bg_pictures.src
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_pictures.title
     *
     * @return the value of bg_pictures.title
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_pictures.title
     *
     * @param title the value for bg_pictures.title
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_pictures.created_by
     *
     * @return the value of bg_pictures.created_by
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_pictures.created_by
     *
     * @param createdBy the value for bg_pictures.created_by
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_pictures.created_at
     *
     * @return the value of bg_pictures.created_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_pictures.created_at
     *
     * @param createdAt the value for bg_pictures.created_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_pictures
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", src=").append(src);
        sb.append(", title=").append(title);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}