package com.mida.chromeext.pojo;

import java.io.Serializable;

public class ContriesSites implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contries_sites.country_id
     *
     * @mbggenerated
     */
    private Byte countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contries_sites.site_id
     *
     * @mbggenerated
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contries_sites
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contries_sites.country_id
     *
     * @return the value of contries_sites.country_id
     *
     * @mbggenerated
     */
    public Byte getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contries_sites.country_id
     *
     * @param countryId the value for contries_sites.country_id
     *
     * @mbggenerated
     */
    public void setCountryId(Byte countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contries_sites.site_id
     *
     * @return the value of contries_sites.site_id
     *
     * @mbggenerated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contries_sites.site_id
     *
     * @param siteId the value for contries_sites.site_id
     *
     * @mbggenerated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contries_sites
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", countryId=").append(countryId);
        sb.append(", siteId=").append(siteId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}