package com.mida.chromeext.pojo;

import java.io.Serializable;
import java.util.Date;

public class SiteViewHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.hid
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private String hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.ip
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.user_id
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.site_id
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.site_title
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private String siteTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.site_url
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private String siteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.times
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private Byte times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.loc
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private String loc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.created_at
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.last_view_time
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private Date lastViewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_view_histories.browser_ua
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private byte[] browserUa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_view_histories
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.hid
     *
     * @return the value of site_view_histories.hid
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public String getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.hid
     *
     * @param hid the value for site_view_histories.hid
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setHid(String hid) {
        this.hid = hid == null ? null : hid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.ip
     *
     * @return the value of site_view_histories.ip
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.ip
     *
     * @param ip the value for site_view_histories.ip
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.user_id
     *
     * @return the value of site_view_histories.user_id
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.user_id
     *
     * @param userId the value for site_view_histories.user_id
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.site_id
     *
     * @return the value of site_view_histories.site_id
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.site_id
     *
     * @param siteId the value for site_view_histories.site_id
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.site_title
     *
     * @return the value of site_view_histories.site_title
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public String getSiteTitle() {
        return siteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.site_title
     *
     * @param siteTitle the value for site_view_histories.site_title
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setSiteTitle(String siteTitle) {
        this.siteTitle = siteTitle == null ? null : siteTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.site_url
     *
     * @return the value of site_view_histories.site_url
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public String getSiteUrl() {
        return siteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.site_url
     *
     * @param siteUrl the value for site_view_histories.site_url
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl == null ? null : siteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.times
     *
     * @return the value of site_view_histories.times
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public Byte getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.times
     *
     * @param times the value for site_view_histories.times
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setTimes(Byte times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.loc
     *
     * @return the value of site_view_histories.loc
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.loc
     *
     * @param loc the value for site_view_histories.loc
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setLoc(String loc) {
        this.loc = loc == null ? null : loc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.created_at
     *
     * @return the value of site_view_histories.created_at
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.created_at
     *
     * @param createdAt the value for site_view_histories.created_at
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.last_view_time
     *
     * @return the value of site_view_histories.last_view_time
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public Date getLastViewTime() {
        return lastViewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.last_view_time
     *
     * @param lastViewTime the value for site_view_histories.last_view_time
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setLastViewTime(Date lastViewTime) {
        this.lastViewTime = lastViewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_view_histories.browser_ua
     *
     * @return the value of site_view_histories.browser_ua
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public byte[] getBrowserUa() {
        return browserUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_view_histories.browser_ua
     *
     * @param browserUa the value for site_view_histories.browser_ua
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    public void setBrowserUa(byte[] browserUa) {
        this.browserUa = browserUa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_view_histories
     *
     * @mbggenerated Sun Sep 15 20:16:48 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hid=").append(hid);
        sb.append(", ip=").append(ip);
        sb.append(", userId=").append(userId);
        sb.append(", siteId=").append(siteId);
        sb.append(", siteTitle=").append(siteTitle);
        sb.append(", siteUrl=").append(siteUrl);
        sb.append(", times=").append(times);
        sb.append(", loc=").append(loc);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", lastViewTime=").append(lastViewTime);
        sb.append(", browserUa=").append(browserUa);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}