package com.mida.chromeext.pojo;

import java.io.Serializable;
import java.util.Date;

public class SiteCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_categories.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_categories.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_categories.sites_count
     *
     * @mbggenerated
     */
    private Integer sitesCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_categories.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_categories.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_categories
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_categories.cid
     *
     * @return the value of site_categories.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_categories.cid
     *
     * @param cid the value for site_categories.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_categories.title
     *
     * @return the value of site_categories.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_categories.title
     *
     * @param title the value for site_categories.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_categories.sites_count
     *
     * @return the value of site_categories.sites_count
     *
     * @mbggenerated
     */
    public Integer getSitesCount() {
        return sitesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_categories.sites_count
     *
     * @param sitesCount the value for site_categories.sites_count
     *
     * @mbggenerated
     */
    public void setSitesCount(Integer sitesCount) {
        this.sitesCount = sitesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_categories.created_at
     *
     * @return the value of site_categories.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_categories.created_at
     *
     * @param createdAt the value for site_categories.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_categories.updated_at
     *
     * @return the value of site_categories.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_categories.updated_at
     *
     * @param updatedAt the value for site_categories.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_categories
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", title=").append(title);
        sb.append(", sitesCount=").append(sitesCount);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}