package com.mida.chromeext.pojo;

import java.io.Serializable;

public class UserSetting implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_settings.sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_settings.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_settings.settings
     *
     * @mbggenerated
     */
    private byte[] settings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_settings
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_settings.sid
     *
     * @return the value of user_settings.sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_settings.sid
     *
     * @param sid the value for user_settings.sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_settings.uid
     *
     * @return the value of user_settings.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_settings.uid
     *
     * @param uid the value for user_settings.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_settings.settings
     *
     * @return the value of user_settings.settings
     *
     * @mbggenerated
     */
    public byte[] getSettings() {
        return settings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_settings.settings
     *
     * @param settings the value for user_settings.settings
     *
     * @mbggenerated
     */
    public void setSettings(byte[] settings) {
        this.settings = settings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_settings
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", uid=").append(uid);
        sb.append(", settings=").append(settings);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}