package com.mida.chromeext.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.number
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gender
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.occupation
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.country_id
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Byte countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.country_name
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.number
     *
     * @return the value of users.number
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.number
     *
     * @param number the value for users.number
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gender
     *
     * @return the value of users.gender
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gender
     *
     * @param gender the value for users.gender
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.occupation
     *
     * @return the value of users.occupation
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.occupation
     *
     * @param occupation the value for users.occupation
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.country_id
     *
     * @return the value of users.country_id
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Byte getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.country_id
     *
     * @param countryId the value for users.country_id
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setCountryId(Byte countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.country_name
     *
     * @return the value of users.country_name
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.country_name
     *
     * @param countryName the value for users.country_name
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Sep 15 20:45:43 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", number=").append(number);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", gender=").append(gender);
        sb.append(", occupation=").append(occupation);
        sb.append(", countryId=").append(countryId);
        sb.append(", countryName=").append(countryName);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}